### ISSUE TITLE
NPM package is out of date

### ISSUE THREAD

**Issue by kym6464** [lydell/json-stringify-pretty-compact#46]
The NPM package is on [v4.0.0](https://github.com/lydell/json-stringify-pretty-compact/releases/tag/v4.0.0) from May 14, 2022. However, there have been several commits since then but never published.

I noticed because of [this](https://github.com/lydell/json-stringify-pretty-compact/commit/c557a343342c975e344fd336bcfd630e2abe16aa) commit in particular, which I stumbled upon because I was about to make a cli wrapper so I started browsing the PRs and found https://github.com/lydell/json-stringify-pretty-compact/pull/41. Would have saved saved a few minutes if the NPM docs were up to date!

**Comment by lydell** [comment]
Hi! The readmes on npm are usually out of date (for most packages), since people rarely make new versions just to update the documentation. These days when making npm packages, I usually just make the readme a link to the github readme, but this package is older than that convention. I’m not making a new version of the package to update the npm readme with that link, sorry.
